export const augmentedRealityProjects = [
    {
        title: "Mini AR Solar System",
        img: "https://laughingsquid.com/wp-content/uploads/2017/03/mini-solar-system.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-one", "tag-four"],
        price: 10,
        rating: 2,
        check: "check-d",
        radio: "radio-e",
        description: "Embark on a celestial journey with the Mini AR Solar System, a captivating DIY project that brings the cosmos to your fingertips, overlaying a virtual solar system on the physical world for an educational and mesmerizing experience.",
        href: "https://www.youtube.com/watch?v=PdpDahp8e-Y"
    },
    {
        title: "Augmented Book Prototype",
        img: "https://content.instructables.com/FIL/GZ7U/IKVI3JRQ/FILGZ7UIKVI3JRQ.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=150",
        category: "cat-b",
        tag: ["tag-one"],
        price: 100,
        rating: 5,
        check: "check-a",
        radio: "radio-e",
        description: "Revolutionize reading with the Augmented Book Prototype, an innovative DIY endeavor that blends the tangible joy of flipping pages with augmented reality enhancements, creating an interactive and immersive literary adventure.",
        href: "https://www.instructables.com/Augmented-Book-Prototype"
    },
    {
        title: "AR Museum",
        img: "https://vrvisiongroup.com/wp-content/uploads/2019/04/ar-museum.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 10,
        rating: 5,
        check: "check-e",
        radio: "radio-a",
        description: "Step into the past and future simultaneously with the AR Museum project, a DIY initiative that transforms static exhibits into dynamic, interactive experiences, using augmented reality to breathe life into history and art.",
        href: "https://www.cerdonis.tech/blogs/how-to-build-an-ar-museum-application"
    },
    {
        title: "AR Game",
        img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/08/24/17/ar.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-four"],
        price: 70,
        rating: 0,
        check: "check-d",
        radio: "radio-b",
        description: "Elevate gaming with the AR Game DIY project, merging the real world with virtual elements for an engaging and interactive gaming experience that transcends traditional boundaries.",
        href: "https://codelabs.developers.google.com/arcore-unity-ar-foundation#0"
    },
    {
        title: "Touchless ATM (IoTAR)",
        img: "https://hackster.imgix.net/uploads/attachments/1264438/_LFxWTCgGw2.blob?auto=compress&w=1600&h=1200&fit=min&fm=jpgg",
        category: "cat-b",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 45,
        rating: 5,
        check: "check-c",
        radio: "radio-a",
        description: "Enhance security and convenience with the Touchless ATM using Augmented Reality (IoTAR), a groundbreaking DIY project that combines augmented reality and IoT to create a secure and hands-free banking experience.",
        href: "https://www.hackster.io/Narensraj/diy-touchless-atm-using-augmented-reality-iotar-e621e0"
    },
    {
        title: "AR to Educate",
        img: "https://elearningindustry.com/wp-content/uploads/2020/12/augmented-reality-in-education.png",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Foster a love for learning with AR to Educate, a DIY initiative that leverages augmented reality to make education more engaging and interactive, bringing subjects to life in a visually immersive way.",
        href: "https://www.hackster.io/claudiuivan1/arte-augmented-reality-to-educate-3a6fd0"
    },
    {
        title: "AR based Navigation System",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNTL-k_nXlT7pxGPs46bsk5wsdTQRHBQP5McjcdLD_ekX9D2izM5nJVsidc5fbRV7zU5Q&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Navigate your surroundings effortlessly with the AR-Based Navigation System DIY project, using augmented reality overlays to provide real-time information and guidance, making everyday navigation intuitive and seamless.",
        href: "https://ssivakumar.medium.com/ar-navigation-d0e0ad406207"
    },
    {
        title: "AR with IoT",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOrAjJZXKBkBVUaKVEgnX-UrNIIc8N2czVOe7audbx-OYxlCVMJc3JFmT-0Cz_0LyAWqA&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Merge the physical and digital realms with AR and Internet of Things (IoT), a DIY project that explores the synergy between augmented reality and smart devices, creating interconnected and responsive environments.",
        href: "https://www.hackster.io/Akshet_Patel/augmented-reality-with-internet-of-things-iot-5af4f7"
    },
    {
        title: "AR Chair Anywhere",
        img: "https://www.fuseanimation.com/wp-content/uploads/2019/03/Furniture-AR-Chair-USDZ-File-in-Office.jpg.webp",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Redefine comfort with the AR Chair Anywhere project, a DIY venture that superimposes virtual seating options into your physical space, offering a customizable and whimsical approach to creating seating arrangements.",
        href: "https://www.hackster.io/the-first-team/chair-anywhere-ee5034"
    },
    {
        title: "AR+DL in Smart Glasses",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw7YxwiqCSNUu1zVST_oX4AIMUrtgsZz1_6E7CUbs0eoDFJ7PvykNn1YYOvxhwhk2xwYU&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Witness the future of smart eyewear with AR+Deep Learning Implementation in Smart Glasses, a cutting-edge DIY project that integrates deep learning technology with augmented reality, bringing a new level of intelligence and interactivity to your everyday eyewear.",
        href: "https://ssivakumar.medium.com/ar-deeplearning-implementation-in-smart-glasses-4b58500afc93"
    },
    {
        title: "VR with Arduino(Processing)",
        img: "https://i.ytimg.com/vi/HEOc6Xc5CAs/maxresdefault.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Transform your surroundings into a digital wonderland with Virtual Reality using Arduino and Processing, a thrilling DIY project that combines hardware tinkering and coding for an immersive experience like never before.",
        href: "https://www.instructables.com/Virtual-Reality-Using-Arduino-and-Processing/"
    },
    {
        title: "VR Skateboard",
        img: "https://png.pngtree.com/background/20240112/original/pngtree-skilled-male-skater-in-virtual-reality-eyewear-gliding-on-skateboard-and-picture-image_7233320.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Take your skateboarding skills to the next level with the VR Skateboard project, merging the physical thrill of riding with a virtual world overlay, creating an exhilarating fusion of reality and imagination.",
        href: "https://www.hackster.io/MatthewHallberg/diy-virtual-reality-skateboard-097bf4"
    },
    {
        title: "Room Based VR Positioning",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRa38s89SS9Cd_UBj2qcW_hqn3iCFj0jcwIgoYjL7dBm2eYZ2L7LEEA-Wy3HyYVoJ64x8&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Explore the future of gaming and interaction with Room-Based VR Positioning, a DIY venture that allows you to navigate virtual realms by mapping and mirroring your physical space for an unparalleled, boundary-breaking VR encounter.",
        href: "https://hackaday.io/project/14977-room-based-vr-positioning"
    },
    {
        title: "VR Glasses",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtfJdHPjx3_DbHEQLIC-03WrEsbfP4AiF9CLm_mgFZHZzUJRtCsBeXNeL8xVPKyYWowqE&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Dive into a world of visual splendor with VR Glasses, a captivating DIY project that lets you craft your personalized virtual reality eyewear, opening a portal to limitless digital adventures.",
        href: "https://hackaday.io/project/10223-vr-glasses"
    },
    {
        title: "Magic VR Hat",
        img: "https://hackster.imgix.net/uploads/attachments/339135/189_F5aTQjBIgL.jpg?auto=compress%2Cformat&w=1280&h=960&fit=max",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Unleash your creativity with the Magic VR Hat, a whimsical DIY project that combines headwear fashion with virtual reality, turning your hat into a mystical gateway to immersive digital realms.",
        href: "https://www.hackster.io/54685/magic-vr-hat-092f5d"
    },
    {
        title: "AR Light Switch",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwAkrWBDG3DII16phdksp-uOs66lYqJ3g_r1KQ9EW-9kc3NDF7EO9XcloVCcpMvJ_hgOg&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Revolutionize your home automation with the AR Light Switch project, merging augmented reality with everyday convenience for a futuristic control experience that seamlessly blends the physical and virtual worlds.",
        href: "https://www.hackster.io/yleguesse/augmented-reality-light-switch-5e8a70"
    },
    {
        title: "Amazon Echo VR Controller",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh9uxy9wuoNhePcor8_etKY8Y8qC558ejBwTA7X2XP9YjwENQfuzxhC5-A9p-t-Nl-OrA&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Elevate your gaming sessions with the Amazon Echo VR Controller DIY project, integrating voice commands and smart technology to enhance your virtual reality interactions and gameplay.",
        href: "https://www.hackster.io/RONDAGDAG/amazon-echo-vr-controller-724c89"
    },
    {
        title: "VR Training Feedback",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrqB7xQ-rEHBEd6tNUtigFeqtAlwfnnXryRVY6qIHqcVZQqsFQRLBUrtAhgumdAGgCaxk&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Sharpen your skills with VR Training Feedback, a DIY initiative that brings a new dimension to learning and skill development by providing real-time feedback in virtual environments.",
        href: "https://hackaday.io/project/11077-vr-training-feedback"
    },
    {
        title: "VR telepresence",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjJ_4UiL0pxJOFZI5AVrX8c3g44RCNHq5ycMxtoGAQGQj1e4xce1cWLbZJnW9qdnGQElo&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Connect with others across distances through VR Telepresence, a DIY venture that combines virtual reality and communication technology to create a shared digital space for immersive remote interactions.",
        href: "https://www.hackster.io/hacky97/vr-telepresence-c59727"
    },
    {
        title: "Color Changing Fireworks in VR",
        img: "https://hackster.imgix.net/uploads/cover_image/file/160072/fireworks21.png?auto=compress%2Cformat&w=900&h=675&fit=min",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Illuminate your virtual celebrations with Color Changing Fireworks in VR, a dazzling DIY project that lets you design and experience vibrant, customizable virtual fireworks displays from the comfort of your own digital space.",
        href: "https://www.hackster.io/RONDAGDAG/color-changing-fireworks-in-virtual-reality-779ea7"
    }
];

export const iotProjects = [
    {
        title: "Smart Doorbell",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Smart-Wi-Fi-Video-Doorbell-using-ESP32-and-Camera_0.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Experience top-tier security with our Smart Wi-Fi Video Doorbell, blending ESP32's power with real-time visuals and interactive features. More than surveillance, it's a holistic approach to home safety.",
        href: "https://circuitdigest.com/microcontroller-projects/diy-smart-wifi-video-doorbell-using-esp32-and-camera"
    },
    {
        title: "Message Lamps",
        img: "https://www.electronicsforu.com/wp-contents/uploads/2018/01/circuit-1.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Connect emotionally through our WiFi-enabled lamps, where a touch conveys feelings globally. Powered by ESP8266, it's a tangible message notifier, lighting up with sentiment intensity and ensuring acknowledged reception.",
        href: "https://www.electronicsforu.com/electronics-projects/prototypes/connected-lamps-esp8266-iot-projects"
    },
    {
        title: "LED Webserver",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/ESP32-LED-Webserver.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Embark on an IoT journey with our ESP32-based DIY LED webserver tutorial, blending theory with hands-on learning. Dive from basics to advanced, ending with both a functional webserver and deepened tech understanding.",
        href: "https://circuitdigest.com/microcontroller-projects/building-diy-led-webserver-with-esp32"
    },
    {
        title: "Pet Feeder",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Automatic-Pet-Feeder.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Simplify pet care with the Blynk Controlled Automatic Pet Feeder, merging IoT convenience with timely feedings. Set schedules, monitor food levels, and ensure your pets never miss a meal, no matter where you are.",
        href: "https://circuitdigest.com/microcontroller-projects/blynk-controlled-automatic-pet-feeder-with-timer"
    },
    {
        title: "Home Automation with AR",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Home-automation-with-Augment-Reality.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Dive into a new era of home automation, combining IoT and Augmented Reality for a transformative experience. Not just control, but visually immerse and interact with every device in your home.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-based-home-automation-with-augmented-reality"
    },
    {
        title: "Smart Garage Door Opener",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/IoT-Smart-Garage-Door-Opener-using-Raspberry-Pi.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Elevate your garage with our IoT-powered opener, harnessing Raspberry Pi for unmatched convenience and security. Control, monitor, and integrate effortlessly for a truly modern home experience.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-smart-garage-door-opener-using-raspberry-pi"
    },
    {
        title: "Real Time GPS Tracker",
        img: "https://how2electronics.com/wp-content/uploads/2022/05/Real-Time-GPS-Tracker-ESP8266-and-Blynk-1080x607.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Track assets and loved ones with precision using our ESP8266-based Real Time GPS Tracker, seamlessly integrated with Blynk. Monitor movements, set geofencing, and access history for safety, logistics, and peace of mind.",
        href: "https://how2electronics.com/real-time-gps-tracker-using-esp8266-blynk-with-maps"
    },
    {
        title: "Smart Parking System",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/IoT-based-Smart-Parking-System-using-ESP8266-NodeMCU.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Navigate urban parking woes with our IoT Smart Parking System, using ESP8266 NodeMCU for real-time space availability. For drivers and managers alike, it simplifies parking and optimizes space management.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-based-smart-parking-system-using-nodemcu"
    },
    {
        title: "Water Quality Monitoring",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Aquaculture-Monitoring-System-using-IoT.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Guard water's purity with our Smart Water Quality Monitoring System, utilizing IoT sensors for real-time quality checks. From public supplies to private pools, ensure safety and proactively address issues with data alerts.",
        href: "https://circuitdigest.com/microcontroller-projects/arduino-nodemcu-based-smart-water-quality-monitoring-system-using-iot"
    },
    {
        title: "Solar Power Monitoring",
        img: "https://how2electronics.com/wp-content/uploads/2022/11/IoT-Solar-Power-Monitoring-System-ESP32-1200x675.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Harness the sun smarter with our ESP32-based IoT system, offering insights into solar power dynamics. Empower your green journey with detailed analytics, optimizing solar efficiency and integration for a brighter tomorrow.",
        href: "https://how2electronics.com/iot-based-solar-power-monitoring-system-with-esp32"
    },
    {
        title: "WiFi Controlled Robot",
        img: "https://how2electronics.com/wp-content/uploads/2021/07/WiFi-Controlled-Robot-1080x607.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "It is a remotely operated device that leverages the ESP8266 WiFi module for wireless communication, enabling control through a smartphone or computer over a WiFi network.",
        href: "https://how2electronics.com/wifi-controlled-robot-using-esp8266-android-app"
    },
    {
        title: "IoT Face Recognition",
        img: "https://i.ytimg.com/vi/XfTvKn3GnOw/maxresdefault.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Discover the future with our Face Recognition AI Robot, blending robotics, AI, and IoT for personalized interactions. Beyond a machine, it showcases tech advancements and the power of human-machine synergy.",
        href: "https://www.electronicsforu.com/electronics-projects/design-iot-face-recognition-ai-robot"
    }
];
export const aiProjects = [
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 1",
        img: "http://via.placeholder.com/1050x700/651FFF/FFFFFF/",
        category: "cat-d",
        tag: ["tag-two"],
        price: 20,
        rating: 5,
        check: "check-b",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 2",
        img: "http://via.placeholder.com/1050x700/607D8B/FFFFFF/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 74,
        rating: 4,
        check: "check-a",
        radio: "radio-b",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
];
export const robotProjects = [
    {
        title: "Brush Bot",
        img: "https://i.ytimg.com/vi/S3GAL2MshCw/maxresdefault.jpg",
        category: "cat-a",
        tag: ["tag-one", "tag-three", "tag-four"],
        price: 0,
        rating: 0,
        check: "check-d",
        radio: "radio-b",
        description: "You may construct brushbots, a straightforward and entertaining form of robot, with crafting supplies.They are simple to construct and don't require any prior robotics knowledge",
        href: "https://www.sciencebuddies.org/stem-activities/brushbot#:~:text=Brushbots%20are%20a%20simple%2C%20fun,even%20make%20them%20sumo%20wrestle!"
    },
    {
        title: "Simple Bots: Clack",
        img: "https://content.instructables.com/F1T/N8XR/KUYDIKE4/F1TN8XRKUYDIKE4.jpg?auto=webp",
        category: "cat-a",
        tag: ["tag-one", "tag-three", "tag-four"],
        price: 0,
        rating: 0,
        check: "check-d",
        radio: "radio-b",
        description: "Clack, the robot, finds beauty in imperfections. With varying wheels, it brings unpredictability and entertainment, celebrating irregularity in a world of precision.",
        href: "https://www.instructables.com/Simple-Bots-Clack"
    },
    {
        title: "Jumping Bot",
        img: "https://www.sciencebuddies.org/A6p9vXnr78rEMQVL9fF_RKxizSQ=/975x698/-/https/www.sciencebuddies.org/cdn/Files/19409/5/jumping-robot.jpg",
        category: "cat-a",
        tag: ["tag-one"],
        price: 70,
        rating: 0,
        check: "check-a",
        radio: "radio-d",
        description: "Engineers mimic nature's jumping abilities in robots, a rare motion in machines, by studying animals and insects, unlocking innovative techniques for improved robotic jumping.",
        href: "https://www.sciencebuddies.org/science-fair-projects/project-ideas/Robotics_p047/robotics/rubber-band-jumping-robot?from=Blog"
    },
    {
        title: "Wash Timer",
        img: "https://hackster.imgix.net/uploads/attachments/1087364/dsc00644_n7gcbzd9Xj.jpeg?auto=compress%2Cformat&w=740&h=555&fit=max",
        category: "cat-a",
        tag: ["tag-one", "tag-three"],
        price: 80,
        rating: 1,
        check: "check-b",
        radio: "radio-b",
        description: "Promote health by washing hands thoroughly for 20 seconds. DIY handwashing timer at home encourages proper hand hygiene for your well-being and others",
        href: "https://www.hackster.io/331510/wash-a-lot-bot-a-diy-hand-washing-timer-2df500"
    },
    {
        title: "Wobbly Robot",
        img: "https://www.sciencebuddies.org/7c8E-ghbyRQlX32OLntTa1o9_xw=/280x0/-/https/www.sciencebuddies.org/cdn/Files/9065/11/bristlebot-robots-trio-1100.png",
        category: "cat-a",
        tag: ["tag-three"],
        price: 90,
        rating: 0,
        check: "check-d",
        radio: "radio-c",
        description: "The Robot is driven by a compact electric motor, which relies on a battery for power. This battery supplies the necessary electrical energy to propel the robot and enable its creative movements.",
        href: "https://www.sciencebuddies.org/science-fair-projects/project-ideas/Robotics_p014/robotics/build-art-bot"
    },
    {
        title: "Mars Rover Robot",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/mars-rover-robot-using-arduino.jpg",
        category: "cat-a",
        tag: ["tag-two", "tag-four"],
        price: 80,
        rating: 5,
        check: "check-a",
        radio: "radio-f",
        description: "This project delves into robotics, demonstrating how to build a versatile Mars rover capable of navigating diverse terrains. Explore the world of autonomous exploration and technological innovation.",
        href: "https://circuitdigest.com/microcontroller-projects/build-your-own-mars-rover-robot-using-arduino"
    },
    {
        "title": "Leaping Robot Frog",
        "img": "https://i.ytimg.com/vi/BxpsfB2kI7I/maxresdefault.jpg",
        "category": "cat-a",
        "tag": ["tag-one", "tag-two", "tag-four"],
        "price": 10,
        "rating": 0,
        "check": "check-d",
        "radio": "radio-c",
        "description": "This robot leaps and bounds akin to a frog, delighting young creators. Its amphibian-like movements provide both entertainment and educational value for budding makers and robot enthusiasts.",
        "href": "https://www.makeuseof.com/11-easy-budget-friendly-robotics-project-ideas-for-kids"
    },
    {
        "title": "Balancing Robot",
        "img": "https://content.instructables.com/ORIG/FLZ/UJAK/KZBA1V8A/FLZUJAKKZBA1V8A.jpg?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300",
        "category": "cat-a",
        "tag": ["tag-one", "tag-four"],
        "price": 50,
        "rating": 5,
        "check": "check-f",
        "radio": "radio-c",
        "description": "Typically, a self-balancing robot requires a microprocessor to function, or more sophisticated electronics like those found in the Segway. This one demonstrates what can be done using just a motor, two switches, and four batteries.",
        "href": "https://maker.pro/analog/projects/balancing-robot-with-no-microcontroller"
    },
    {
        "title": "Voice Controlled Robot",
        "img": "https://hackster.imgix.net/uploads/attachments/1441943/_yungsjjK9v.blob?auto=compress%2Cformat&w=900&h=675&fit=min",
        "category": "cat-a",
        "tag": ["tag-four"],
        "price": 45,
        "rating": 0,
        "check": "check-b",
        "radio": "radio-a",
        "description": "Users can take charge of the robot's actions with custom voice commands. This interactive feature empowers users to direct and personalize the robot's movements, enhancing the overall experience.",
        "href": "https://maker.pro/arduino/projects/diy-arduino-voice-controlled-robot"
    },
    {
        "title": "Four Legged Walking Robot",
        "img": "https://www.sciencebuddies.org/BUzRGlRF2PAY1j11v5q-J2oNUwA=/650x304/-/https/www.sciencebuddies.org/cdn/Files/19831/5/simple-walking-robots.jpg",
        "category": "cat-a",
        "tag": ["tag-one", "tag-three", "tag-four"],
        "price": 0,
        "rating": 0,
        "check": "check-d",
        "radio": "radio-b",
        "description": "It may sound difficult for kids to build a four-legged, walking robot, but it isn't. The simplicity of each stage ensures that children won't quitup in the middle of the process.",
        "href": "https://www.youtube.com/watch?v=wY08f3MIDnc&t=54s"
    },
    {
        "title": "Solar Vacuum Cleaner Robot",
        "img": "https://nevonprojects.com/wp-content/uploads/2021/02/nevon-solar-floor-cleaner-web.jpg",
        "category": "cat-a",
        "tag": ["tag-one", "tag-three", "tag-four"],
        "price": 0,
        "rating": 0,
        "check": "check-d",
        "radio": "radio-b",
        "description": "A floor-cleaning robot powered by solar energy that makes it simple to clean outside areas, terraces, open restaurants, big campuses, etc. The method is designed to make it easier for cleaners to clean big, open spaces without exerting any physical effort or requiring frequent robot charging.",
        "href": "https://nevonprojects.com/solar-vacuum-cleaner-floor-cleaner-robot"
    },
    {
        "title": "Soccer Robot (ESP32-CAM)",
        "img": "https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2021/01/ESP32-CAM-Remote-Controlled-Robot-Assembled.jpg?resize=750%2C421&quality=100&strip=all&ssl=1",
        "category": "cat-a",
        "tag": ["tag-one", "tag-three", "tag-four"],
        "price": 0,
        "rating": 0,
        "check": "check-d",
        "radio": "radio-b",
        "description": "This robot can play football by dribbling and kicking the ball. You can create a lot of them and play robot football matches because it is controlled using a smartphone with a wireless bluetooth connection!",
        "href": "https://maker.pro/everything-esp/projects/esp32-cam-video-surveillance-robot"
    }
];
export const mlProjects = [
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 1",
        img: "http://via.placeholder.com/1050x700/651FFF/FFFFFF/",
        category: "cat-d",
        tag: ["tag-two"],
        price: 20,
        rating: 5,
        check: "check-b",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 2",
        img: "http://via.placeholder.com/1050x700/607D8B/FFFFFF/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 74,
        rating: 4,
        check: "check-a",
        radio: "radio-b",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Machine Learning 1",
        img: "http://via.placeholder.com/1050x700/757575/FFFFFF/",
        category: "cat-e",
        tag: ["tag-one", "tag-three"],
        price: 5,
        rating: 4,
        check: "check-a",
        radio: "radio-b",
        description: "connection!",
        href: "https"
    },

    {
        title: "Machine Learning 2",
        img: "http://via.placeholder.com/1050x700/E1BEE7/767676/",
        category: "cat-e",
        tag: ["tag-one", "tag-three"],
        price: 55,
        rating: 2,
        check: "check-e",
        radio: "radio-d",
        description: "connection!",
        href: "https"
    },
];

export const cyberSecurity = [
    {
        title: "Cyber Security 1",
        img: "http://via.placeholder.com/1050x700/AA00FF/FFFFFF/",
        category: "cat-f",
        tag: ["tag-one", "tag-two"],
        price: 20,
        rating: 0,
        check: "check-b",
        radio: "radio-e",
        description: "connection!",
        href: "https"
    },
    {
        title: "Cyber Security 2",
        img: "http://via.placeholder.com/1050x700/E1BEE7/767676/",
        category: "cat-f",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 40,
        rating: 0,
        check: "check-c",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Cyber Security 3",
        img: "http://via.placeholder.com/1050x700/388E3C/FFFFFF/",
        category: "cat-f",
        tag: ["tag-one", "tag-two"],
        price: 20,
        rating: 3,
        check: "check-a",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    }
]

export const All = [
    {
        title: "Smart Doorbell",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Smart-Wi-Fi-Video-Doorbell-using-ESP32-and-Camera_0.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Experience top-tier security with our Smart Wi-Fi Video Doorbell, blending ESP32's power with real-time visuals and interactive features. More than surveillance, it's a holistic approach to home safety.",
        href: "https://circuitdigest.com/microcontroller-projects/diy-smart-wifi-video-doorbell-using-esp32-and-camera"
    },
    {
        title: "Message Lamps",
        img: "https://www.electronicsforu.com/wp-contents/uploads/2018/01/circuit-1.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Connect emotionally through our WiFi-enabled lamps, where a touch conveys feelings globally. Powered by ESP8266, it's a tangible message notifier, lighting up with sentiment intensity and ensuring acknowledged reception.",
        href: "https://www.electronicsforu.com/electronics-projects/prototypes/connected-lamps-esp8266-iot-projects"
    },
    {
        title: "LED Webserver",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/ESP32-LED-Webserver.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Embark on an IoT journey with our ESP32-based DIY LED webserver tutorial, blending theory with hands-on learning. Dive from basics to advanced, ending with both a functional webserver and deepened tech understanding.",
        href: "https://circuitdigest.com/microcontroller-projects/building-diy-led-webserver-with-esp32"
    },
    {
        title: "Pet Feeder",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Automatic-Pet-Feeder.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Simplify pet care with the Blynk Controlled Automatic Pet Feeder, merging IoT convenience with timely feedings. Set schedules, monitor food levels, and ensure your pets never miss a meal, no matter where you are.",
        href: "https://circuitdigest.com/microcontroller-projects/blynk-controlled-automatic-pet-feeder-with-timer"
    },
    {
        title: "Home Automation with AR",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Home-automation-with-Augment-Reality.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Dive into a new era of home automation, combining IoT and Augmented Reality for a transformative experience. Not just control, but visually immerse and interact with every device in your home.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-based-home-automation-with-augmented-reality"
    },
    {
        title: "Smart Garage Door Opener",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/IoT-Smart-Garage-Door-Opener-using-Raspberry-Pi.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Elevate your garage with our IoT-powered opener, harnessing Raspberry Pi for unmatched convenience and security. Control, monitor, and integrate effortlessly for a truly modern home experience.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-smart-garage-door-opener-using-raspberry-pi"
    },
    {
        title: "Real Time GPS Tracker",
        img: "https://how2electronics.com/wp-content/uploads/2022/05/Real-Time-GPS-Tracker-ESP8266-and-Blynk-1080x607.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Track assets and loved ones with precision using our ESP8266-based Real Time GPS Tracker, seamlessly integrated with Blynk. Monitor movements, set geofencing, and access history for safety, logistics, and peace of mind.",
        href: "https://how2electronics.com/real-time-gps-tracker-using-esp8266-blynk-with-maps"
    },
    {
        title: "Smart Parking System",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/IoT-based-Smart-Parking-System-using-ESP8266-NodeMCU.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Navigate urban parking woes with our IoT Smart Parking System, using ESP8266 NodeMCU for real-time space availability. For drivers and managers alike, it simplifies parking and optimizes space management.",
        href: "https://circuitdigest.com/microcontroller-projects/iot-based-smart-parking-system-using-nodemcu"
    },
    {
        title: "Water Quality Monitoring",
        img: "https://circuitdigest.com/sites/default/files/projectimage_mic/Aquaculture-Monitoring-System-using-IoT.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Guard water's purity with our Smart Water Quality Monitoring System, utilizing IoT sensors for real-time quality checks. From public supplies to private pools, ensure safety and proactively address issues with data alerts.",
        href: "https://circuitdigest.com/microcontroller-projects/arduino-nodemcu-based-smart-water-quality-monitoring-system-using-iot"
    },
    {
        title: "Solar Power Monitoring",
        img: "https://how2electronics.com/wp-content/uploads/2022/11/IoT-Solar-Power-Monitoring-System-ESP32-1200x675.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Harness the sun smarter with our ESP32-based IoT system, offering insights into solar power dynamics. Empower your green journey with detailed analytics, optimizing solar efficiency and integration for a brighter tomorrow.",
        href: "https://how2electronics.com/iot-based-solar-power-monitoring-system-with-esp32"
    },
    {
        title: "WiFi Controlled Robot",
        img: "https://how2electronics.com/wp-content/uploads/2021/07/WiFi-Controlled-Robot-1080x607.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "It is a remotely operated device that leverages the ESP8266 WiFi module for wireless communication, enabling control through a smartphone or computer over a WiFi network.",
        href: "https://how2electronics.com/wifi-controlled-robot-using-esp8266-android-app"
    },
    {
        title: "IoT Face Recognition",
        img: "https://i.ytimg.com/vi/XfTvKn3GnOw/maxresdefault.jpg",
        category: "cat-c",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Discover the future with our Face Recognition AI Robot, blending robotics, AI, and IoT for personalized interactions. Beyond a machine, it showcases tech advancements and the power of human-machine synergy.",
        href: "https://www.electronicsforu.com/electronics-projects/design-iot-face-recognition-ai-robot"
    },
    {
        title: "Mini AR Solar System",
        img: "https://laughingsquid.com/wp-content/uploads/2017/03/mini-solar-system.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-one", "tag-four"],
        price: 10,
        rating: 2,
        check: "check-d",
        radio: "radio-e",
        description: "Embark on a celestial journey with the Mini AR Solar System, a captivating DIY project that brings the cosmos to your fingertips, overlaying a virtual solar system on the physical world for an educational and mesmerizing experience.",
        href: "https://www.youtube.com/watch?v=PdpDahp8e-Y"
    },
    {
        title: "Augmented Book Prototype",
        img: "https://content.instructables.com/FIL/GZ7U/IKVI3JRQ/FILGZ7UIKVI3JRQ.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=150",
        category: "cat-b",
        tag: ["tag-one"],
        price: 100,
        rating: 5,
        check: "check-a",
        radio: "radio-e",
        description: "Revolutionize reading with the Augmented Book Prototype, an innovative DIY endeavor that blends the tangible joy of flipping pages with augmented reality enhancements, creating an interactive and immersive literary adventure.",
        href: "https://www.instructables.com/Augmented-Book-Prototype"
    },
    {
        title: "AR Museum",
        img: "https://vrvisiongroup.com/wp-content/uploads/2019/04/ar-museum.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 10,
        rating: 5,
        check: "check-e",
        radio: "radio-a",
        description: "Step into the past and future simultaneously with the AR Museum project, a DIY initiative that transforms static exhibits into dynamic, interactive experiences, using augmented reality to breathe life into history and art.",
        href: "https://www.cerdonis.tech/blogs/how-to-build-an-ar-museum-application"
    },
    {
        title: "AR Game",
        img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/08/24/17/ar.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-four"],
        price: 70,
        rating: 0,
        check: "check-d",
        radio: "radio-b",
        description: "Elevate gaming with the AR Game DIY project, merging the real world with virtual elements for an engaging and interactive gaming experience that transcends traditional boundaries.",
        href: "https://codelabs.developers.google.com/arcore-unity-ar-foundation#0"
    },
    {
        title: "Touchless ATM (IoTAR)",
        img: "https://hackster.imgix.net/uploads/attachments/1264438/_LFxWTCgGw2.blob?auto=compress&w=1600&h=1200&fit=min&fm=jpgg",
        category: "cat-b",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 45,
        rating: 5,
        check: "check-c",
        radio: "radio-a",
        description: "Enhance security and convenience with the Touchless ATM using Augmented Reality (IoTAR), a groundbreaking DIY project that combines augmented reality and IoT to create a secure and hands-free banking experience.",
        href: "https://www.hackster.io/Narensraj/diy-touchless-atm-using-augmented-reality-iotar-e621e0"
    },
    {
        title: "AR to Educate",
        img: "https://elearningindustry.com/wp-content/uploads/2020/12/augmented-reality-in-education.png",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Foster a love for learning with AR to Educate, a DIY initiative that leverages augmented reality to make education more engaging and interactive, bringing subjects to life in a visually immersive way.",
        href: "https://www.hackster.io/claudiuivan1/arte-augmented-reality-to-educate-3a6fd0"
    },
    {
        title: "AR based Navigation System",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNTL-k_nXlT7pxGPs46bsk5wsdTQRHBQP5McjcdLD_ekX9D2izM5nJVsidc5fbRV7zU5Q&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Navigate your surroundings effortlessly with the AR-Based Navigation System DIY project, using augmented reality overlays to provide real-time information and guidance, making everyday navigation intuitive and seamless.",
        href: "https://ssivakumar.medium.com/ar-navigation-d0e0ad406207"
    },
    {
        title: "AR with IoT",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOrAjJZXKBkBVUaKVEgnX-UrNIIc8N2czVOe7audbx-OYxlCVMJc3JFmT-0Cz_0LyAWqA&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Merge the physical and digital realms with AR and Internet of Things (IoT), a DIY project that explores the synergy between augmented reality and smart devices, creating interconnected and responsive environments.",
        href: "https://www.hackster.io/Akshet_Patel/augmented-reality-with-internet-of-things-iot-5af4f7"
    },
    {
        title: "AR Chair Anywhere",
        img: "https://www.fuseanimation.com/wp-content/uploads/2019/03/Furniture-AR-Chair-USDZ-File-in-Office.jpg.webp",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Redefine comfort with the AR Chair Anywhere project, a DIY venture that superimposes virtual seating options into your physical space, offering a customizable and whimsical approach to creating seating arrangements.",
        href: "https://www.hackster.io/the-first-team/chair-anywhere-ee5034"
    },
    {
        title: "AR+DL in Smart Glasses",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw7YxwiqCSNUu1zVST_oX4AIMUrtgsZz1_6E7CUbs0eoDFJ7PvykNn1YYOvxhwhk2xwYU&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Witness the future of smart eyewear with AR+Deep Learning Implementation in Smart Glasses, a cutting-edge DIY project that integrates deep learning technology with augmented reality, bringing a new level of intelligence and interactivity to your everyday eyewear.",
        href: "https://ssivakumar.medium.com/ar-deeplearning-implementation-in-smart-glasses-4b58500afc93"
    },
    {
        title: "VR with Arduino(Processing)",
        img: "https://i.ytimg.com/vi/HEOc6Xc5CAs/maxresdefault.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Transform your surroundings into a digital wonderland with Virtual Reality using Arduino and Processing, a thrilling DIY project that combines hardware tinkering and coding for an immersive experience like never before.",
        href: "https://www.instructables.com/Virtual-Reality-Using-Arduino-and-Processing/"
    },
    {
        title: "VR Skateboard",
        img: "https://png.pngtree.com/background/20240112/original/pngtree-skilled-male-skater-in-virtual-reality-eyewear-gliding-on-skateboard-and-picture-image_7233320.jpg",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Take your skateboarding skills to the next level with the VR Skateboard project, merging the physical thrill of riding with a virtual world overlay, creating an exhilarating fusion of reality and imagination.",
        href: "https://www.hackster.io/MatthewHallberg/diy-virtual-reality-skateboard-097bf4"
    },
    {
        title: "Room Based VR Positioning",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRa38s89SS9Cd_UBj2qcW_hqn3iCFj0jcwIgoYjL7dBm2eYZ2L7LEEA-Wy3HyYVoJ64x8&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Explore the future of gaming and interaction with Room-Based VR Positioning, a DIY venture that allows you to navigate virtual realms by mapping and mirroring your physical space for an unparalleled, boundary-breaking VR encounter.",
        href: "https://hackaday.io/project/14977-room-based-vr-positioning"
    },
    {
        title: "VR Glasses",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtfJdHPjx3_DbHEQLIC-03WrEsbfP4AiF9CLm_mgFZHZzUJRtCsBeXNeL8xVPKyYWowqE&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Dive into a world of visual splendor with VR Glasses, a captivating DIY project that lets you craft your personalized virtual reality eyewear, opening a portal to limitless digital adventures.",
        href: "https://hackaday.io/project/10223-vr-glasses"
    },
    {
        title: "Magic VR Hat",
        img: "https://hackster.imgix.net/uploads/attachments/339135/189_F5aTQjBIgL.jpg?auto=compress%2Cformat&w=1280&h=960&fit=max",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Unleash your creativity with the Magic VR Hat, a whimsical DIY project that combines headwear fashion with virtual reality, turning your hat into a mystical gateway to immersive digital realms.",
        href: "https://www.hackster.io/54685/magic-vr-hat-092f5d"
    },
    {
        title: "AR Light Switch",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwAkrWBDG3DII16phdksp-uOs66lYqJ3g_r1KQ9EW-9kc3NDF7EO9XcloVCcpMvJ_hgOg&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Revolutionize your home automation with the AR Light Switch project, merging augmented reality with everyday convenience for a futuristic control experience that seamlessly blends the physical and virtual worlds.",
        href: "https://www.hackster.io/yleguesse/augmented-reality-light-switch-5e8a70"
    },
    {
        title: "Amazon Echo VR Controller",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh9uxy9wuoNhePcor8_etKY8Y8qC558ejBwTA7X2XP9YjwENQfuzxhC5-A9p-t-Nl-OrA&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Elevate your gaming sessions with the Amazon Echo VR Controller DIY project, integrating voice commands and smart technology to enhance your virtual reality interactions and gameplay.",
        href: "https://www.hackster.io/RONDAGDAG/amazon-echo-vr-controller-724c89"
    },
    {
        title: "VR Training Feedback",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrqB7xQ-rEHBEd6tNUtigFeqtAlwfnnXryRVY6qIHqcVZQqsFQRLBUrtAhgumdAGgCaxk&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Sharpen your skills with VR Training Feedback, a DIY initiative that brings a new dimension to learning and skill development by providing real-time feedback in virtual environments.",
        href: "https://hackaday.io/project/11077-vr-training-feedback"
    },
    {
        title: "VR telepresence",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjJ_4UiL0pxJOFZI5AVrX8c3g44RCNHq5ycMxtoGAQGQj1e4xce1cWLbZJnW9qdnGQElo&usqp=CAU",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Connect with others across distances through VR Telepresence, a DIY venture that combines virtual reality and communication technology to create a shared digital space for immersive remote interactions.",
        href: "https://www.hackster.io/hacky97/vr-telepresence-c59727"
    },
    {
        title: "Color Changing Fireworks in VR",
        img: "https://hackster.imgix.net/uploads/cover_image/file/160072/fireworks21.png?auto=compress%2Cformat&w=900&h=675&fit=min",
        category: "cat-b",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "Illuminate your virtual celebrations with Color Changing Fireworks in VR, a dazzling DIY project that lets you design and experience vibrant, customizable virtual fireworks displays from the comfort of your own digital space.",
        href: "https://www.hackster.io/RONDAGDAG/color-changing-fireworks-in-virtual-reality-779ea7"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "VR telepresence",
        img: "https://www",
        category: "cat-d",
        tag: ["tag-one", "tag-two"],
        price: 70,
        rating: 5,
        check: "check-c",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 1",
        img: "http://via.placeholder.com/1050x700/651FFF/FFFFFF/",
        category: "cat-d",
        tag: ["tag-two"],
        price: 20,
        rating: 5,
        check: "check-b",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 2",
        img: "http://via.placeholder.com/1050x700/607D8B/FFFFFF/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 74,
        rating: 4,
        check: "check-a",
        radio: "radio-b",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Artificial Intelligence 3",
        img: "http://via.placeholder.com/1050x700/FFE57F/767676/",
        category: "cat-d",
        tag: ["tag-one", "tag-three"],
        price: 40,
        rating: 4,
        check: "check-d",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    }, {
        title: "Machine Learning 1",
        img: "http://via.placeholder.com/1050x700/757575/FFFFFF/",
        category: "cat-e",
        tag: ["tag-one", "tag-three"],
        price: 5,
        rating: 4,
        check: "check-a",
        radio: "radio-b",
        description: "connection!",
        href: "https"
    },

    {
        title: "Machine Learning 2",
        img: "http://via.placeholder.com/1050x700/E1BEE7/767676/",
        category: "cat-e",
        tag: ["tag-one", "tag-three"],
        price: 55,
        rating: 2,
        check: "check-e",
        radio: "radio-d",
        description: "connection!",
        href: "https"
    },
    {
        title: "Cyber Security 1",
        img: "http://via.placeholder.com/1050x700/AA00FF/FFFFFF/",
        category: "cat-f",
        tag: ["tag-one", "tag-two"],
        price: 20,
        rating: 0,
        check: "check-b",
        radio: "radio-e",
        description: "connection!",
        href: "https"
    },
    {
        title: "Cyber Security 2",
        img: "http://via.placeholder.com/1050x700/E1BEE7/767676/",
        category: "cat-f",
        tag: ["tag-one", "tag-two", "tag-four"],
        price: 40,
        rating: 0,
        check: "check-c",
        radio: "radio-a",
        description: "connection!",
        href: "https"
    },
    {
        title: "Cyber Security 3",
        img: "http://via.placeholder.com/1050x700/388E3C/FFFFFF/",
        category: "cat-f",
        tag: ["tag-one", "tag-two"],
        price: 20,
        rating: 3,
        check: "check-a",
        radio: "radio-c",
        description: "connection!",
        href: "https"
    }
]


